<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
abstract class BaseAdmin extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('admin');
        $this->hasColumn('id', 'integer', 8, array('type' => 'integer', 'unsigned' => '1', 'primary' => true, 'autoincrement' => true, 'length' => '8'));
        $this->hasColumn('login', 'string', 20, array('type' => 'string', 'default' => '', 'notnull' => true, 'length' => '20'));
        $this->hasColumn('haslo', 'string', 32, array('type' => 'string', 'default' => '', 'notnull' => true, 'length' => '32'));
        $this->hasColumn('created_at', 'timestamp', 25, array('type' => 'timestamp', 'notnull' => true, 'length' => '25'));
        $this->hasColumn('updated_at', 'timestamp', 25, array('type' => 'timestamp', 'default' => '0000-00-00 00:00:00', 'notnull' => true, 'length' => '25'));
    }

    public function setUp()
    {
        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}