<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
abstract class BaseKandydat extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('kandydat');
        $this->hasColumn('id', 'integer', 4, array('type' => 'integer', 'primary' => true, 'autoincrement' => true, 'length' => '4'));
        $this->hasColumn('imiona', 'string', 80, array('type' => 'string', 'notnull' => true, 'length' => '80'));
        $this->hasColumn('nazwisko', 'string', 80, array('type' => 'string', 'notnull' => true, 'length' => '80'));
        $this->hasColumn('plec', 'integer', 1, array('type' => 'integer', 'notnull' => true, 'length' => '1'));
        $this->hasColumn('kierunek', 'string', 30, array('type' => 'string', 'notnull' => true, 'length' => '30'));
        $this->hasColumn('stacjonarne', 'integer', 1, array('type' => 'integer', 'default' => '1', 'length' => '1'));
        $this->hasColumn('studia_typ', 'string', 15, array('type' => 'string', 'default' => 'inz', 'notnull' => true, 'length' => '15'));
        $this->hasColumn('urodzenie_miejsce', 'string', 40, array('type' => 'string', 'notnull' => true, 'length' => '40'));
        $this->hasColumn('matka_imie', 'string', 40, array('type' => 'string', 'default' => '', 'notnull' => true, 'length' => '40'));
        $this->hasColumn('ojciec_imie', 'string', 40, array('type' => 'string', 'notnull' => true, 'length' => '40'));
        $this->hasColumn('narodowosc', 'string', 40, array('type' => 'string', 'notnull' => true, 'length' => '40'));
        $this->hasColumn('obywatelstwo', 'string', 40, array('type' => 'string', 'notnull' => true, 'length' => '40'));
        $this->hasColumn('pesel', 'string', 11, array('type' => 'string', 'length' => '11'));
        $this->hasColumn('dowod_osobisty_nr', 'string', 10, array('type' => 'string', 'notnull' => true, 'length' => '10'));
        $this->hasColumn('zameldowanie_dom_nr', 'string', 6, array('type' => 'string', 'length' => '6'));
        $this->hasColumn('zameldowanie_kod', 'string', 6, array('type' => 'string', 'length' => '6'));
        $this->hasColumn('stosunek_do_sluzby_wojskowej', 'string', 20, array('type' => 'string', 'notnull' => true, 'length' => '20'));
        $this->hasColumn('niepelnosprawny', 'boolean', 1, array('type' => 'boolean', 'default' => 0, 'length' => '1'));
        $this->hasColumn('login', 'string', 20, array('type' => 'string', 'notnull' => true, 'length' => '20'));
        $this->hasColumn('haslo', 'string', 32, array('type' => 'string', 'notnull' => true, 'length' => '32'));
        $this->hasColumn('created_at', 'timestamp', 25, array('type' => 'timestamp', 'notnull' => true, 'length' => '25'));
        $this->hasColumn('updated_at', 'timestamp', 25, array('type' => 'timestamp', 'default' => '0000-00-00 00:00:00', 'notnull' => true, 'length' => '25'));
        $this->hasColumn('zameldowanie_miasto', 'string', 30, array('type' => 'string', 'notnull' => true, 'length' => '30'));
        $this->hasColumn('zameldowanie_wojewodztwo', 'string', 30, array('type' => 'string', 'notnull' => true, 'length' => '30'));
        $this->hasColumn('email', 'string', 255, array('type' => 'string', 'notnull' => true, 'length' => '255'));
        $this->hasColumn('telefon_nr', 'string', 12, array('type' => 'string', 'notnull' => true, 'length' => '12'));
        $this->hasColumn('nip', 'string', 20, array('type' => 'string', 'length' => '20'));
        $this->hasColumn('zameldowanie_ulica', 'string', 45, array('type' => 'string', 'length' => '45'));
        $this->hasColumn('specjalnosc', 'string', 60, array('type' => 'string', 'length' => '60'));
        $this->hasColumn('jezyk', 'string', 20, array('type' => 'string', 'length' => '20'));
        $this->hasColumn('jezyk2', 'string', 20, array('type' => 'string', 'length' => '20'));
        $this->hasColumn('zameldowanie_mieszkanie_nr', 'string', 6, array('type' => 'string', 'length' => '6'));
        $this->hasColumn('korespondencja_ulica', 'string', 45, array('type' => 'string', 'length' => '45'));
        $this->hasColumn('korespondencja_dom_nr', 'string', 6, array('type' => 'string', 'length' => '6'));
        $this->hasColumn('korespondencja_mieszkanie_nr', 'string', 6, array('type' => 'string', 'length' => '6'));
        $this->hasColumn('korespondencja_kod', 'string', 6, array('type' => 'string', 'length' => '6'));
        $this->hasColumn('ksiazeczka_wojskowa_nr', 'string', 20, array('type' => 'string', 'length' => '20'));
        $this->hasColumn('szkola_srednia_rok_ukonczenia', 'string', 4, array('type' => 'string', 'length' => '4'));
        $this->hasColumn('szkola_srednia', 'string', 255, array('type' => 'string', 'notnull' => true, 'length' => '255'));
        $this->hasColumn('inne_studia', 'string', 255, array('type' => 'string', 'length' => '255'));
        $this->hasColumn('plywanie_grupa', 'string', 20, array('type' => 'string', 'length' => '20'));
        $this->hasColumn('skad_wiem', 'string', 40, array('type' => 'string', 'length' => '40'));
        $this->hasColumn('skonczone_studia', 'string', 80, array('type' => 'string', 'length' => '80'));
        $this->hasColumn('skonczone_studia_rok_ukonczenia', 'string', 4, array('type' => 'string', 'length' => '4'));
        $this->hasColumn('zdjecie', 'string', 255, array('type' => 'string', 'length' => '255'));
        $this->hasColumn('korespondencja_miasto', 'string', 30, array('type' => 'string', 'length' => '30'));
        $this->hasColumn('korespondencja_wojewodztwo', 'string', 30, array('type' => 'string', 'length' => '30'));
        $this->hasColumn('mobile_nr', 'string', 12, array('type' => 'string', 'length' => '12'));
        $this->hasColumn('wku_miasto', 'string', 60, array('type' => 'string', 'length' => '60'));
        $this->hasColumn('szkola_komentarz', 'string', 255, array('type' => 'string', 'length' => '255'));
        $this->hasColumn('przelew_zaksiegowany', 'boolean', 1, array('type' => 'boolean', 'default' => 0, 'length' => '1'));
        $this->hasColumn('dokumenty_dotarly', 'boolean', 1, array('type' => 'boolean', 'default' => 0, 'length' => '1'));
        $this->hasColumn('pytanie_haslo', 'string', 80, array('type' => 'string', 'notnull' => true, 'length' => '80'));
        $this->hasColumn('odpowiedz_haslo', 'string', 25, array('type' => 'string', 'notnull' => true, 'length' => '25'));
    }

    public function setUp()
    {
        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}