<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2012/05/31 16:50:45

return array(
'propel' => new sfDoctrineDatabase(array (
  'classname' => 'DoctrinePDO',
  'dsn' => 'mysql:dbname=rekrutacja;host=mysql.fr.pl',
  'username' => 'rekrutacja',
  'password' => 'QaZx123',
  'encoding' => 'utf8',
  'persistent' => true,
  'pooling' => true,
  'name' => 'propel',
)),);
