<?php
// auto-generated by sfRoutingConfigHandler
// date: 2012/05/31 16:50:45
return array(
'login' => new sfRoute('/login', array (
  'module' => 'login',
  'action' => 'index',
), array (
), array (
)),
'logout' => new sfRoute('/logout', array (
  'module' => 'login',
  'action' => 'logout',
), array (
), array (
)),
'homepage' => new sfRoute('/', array (
  'module' => 'kandydat',
  'action' => 'new',
), array (
), array (
)),
'default_index' => new sfRoute('/:module', array (
  'action' => 'index',
), array (
), array (
)),
'default' => new sfRoute('/:module/:action/*', array (
), array (
), array (
)),
);
