<?php
// auto-generated by sfSecurityConfigHandler
// date: 2012/05/31 16:50:45
$this->security = array (
  'info' => 
  array (
    'is_secure' => false,
  ),
  'all' => 
  array (
    'is_secure' => false,
  ),
);
