<?php
// auto-generated by sfSecurityConfigHandler
// date: 2012/05/31 16:50:45
$this->security = array (
  'new' => 
  array (
    'is_secure' => false,
  ),
  'create' => 
  array (
    'is_secure' => false,
  ),
  'remind1' => 
  array (
    'is_secure' => false,
  ),
  'remind2' => 
  array (
    'is_secure' => false,
  ),
  'all' => 
  array (
    'is_secure' => true,
  ),
);
