<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class AdminTable extends Doctrine_Table {

	public function getByLoginAndPassword($login, $password) {
	    $q = $this->createQuery('a')
	      ->where('a.login = ?', $login)
	      ->addWhere('a.haslo = ?', md5($password));
	    return $q->execute();				
	}

}