<?php


/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Kandydat extends BaseKandydat {

	public function getPlecString() {
		$plec_lista = Doctrine :: getTable('Kandydat')->getPlecLista();
		return array_key_exists((int) $this->getPlec(), $plec_lista) ? $plec_lista[$this->getPlec()] : 'N/A';
	}

	public function getStudiaTypString() {
		$typ_studiow_lista = Doctrine :: getTable('Kandydat')->getTypStudiowLista();
		return array_key_exists($this->getStudiaTyp(), $typ_studiow_lista) ? $typ_studiow_lista[$this->getStudiaTyp()] : 'N/A';
	}

	public function getStacjonarneString() {
		if ($this->getStacjonarne() == 'stacjonarne' || $this->getStacjonarne() == '0' || $this->getStacjonarne() == 0)
			return 'stacjonarne';
		else
			return 'niestacjonarne';
	}

	public function getKierunekString() {
		$kierunek_lista = Doctrine :: getTable('Kandydat')->getKierunekLista();
		return array_key_exists($this->getKierunek(), $kierunek_lista) ? $kierunek_lista[$this->getKierunek()] : 'N/A';
	}

	public function getSpecjalnoscString() {
		$specjalnosc_lista = Doctrine :: getTable('Kandydat')->getSpecjalnoscLista();
		return array_key_exists($this->getSpecjalnosc(), $specjalnosc_lista) ? $specjalnosc_lista[$this->getSpecjalnosc()] : 'N/A';
	}

	public function setHaslo($v) {
		return $this->_set('haslo', md5($v));
	}
}