<?php
if(!defined('FONT_CONFIG')){
define('FONT_CONFIG',1) ;
// Definiowanie poszczególnych fontów
define('SANS','DejaVuSans') ;
define('SANSBI','DejaVuSans-BoldOblique') ;
define('SANSB','DejaVuSans-Bold') ;
define('SANSEL','DejaVuSans-ExtraLight') ;
define('SANSI','DejaVuSans-Oblique') ;

define('SANSCBI','DejaVuSansCondensed-BoldOblique') ;
define('SANSCB','DejaVuSansCondensed-Bold') ;
define('SANSCI','DejaVuSansCondensed-Oblique') ;
define('SANSC','DejaVuSansCondensed') ;

define('SANSMBI','DejaVuSansMono-BoldOblique') ;
define('SANSMB','DejaVuSansMono-Bold') ;
define('SANSMI','DejaVuSansMono-Oblique') ;

define('SERIF','DejaVuSerif') ;
define('SERIFBI','DejaVuSerif-BoldOblique') ;
define('SERIFB','DejaVuSerif-Bold') ;
define('SERIFI','DejaVuSerif-Oblique') ;

define('SERIFCBI','DejaVuSerifCondensed-BoldOblique') ;
define('SERIFCB','DejaVuSerifCondensed-Bold') ;
define('SERIFCI','DejaVuSerifCondensed-Oblique') ;
define('SERIFC','DejaVuSerifCondensed') ;

}
?>