dev:
  propel:
    param:
      classname:  DebugPDO

test:
  propel:
    param:
      classname:  DebugPDO

all:
  propel:
    class:        sfDoctrineDatabase
    param:
      classname:  DoctrinePDO
      dsn:        mysql:dbname=rekrutacja;host=mysql.fr.pl
      username:   rekrutacja
      password:   QaZx123
      encoding:   utf8
      persistent: true
      pooling:    true
