CREATE TABLE kandydat (
	id INT AUTO_INCREMENT NOT NULL, 
	imiona VARCHAR(80) NOT NULL, 
	nazwisko VARCHAR(80) NOT NULL,
	email VARCHAR(255) NOT NULL,
	plec BOOLEAN NOT NULL, 
	matka_imie VARCHAR(40) NOT NULL, 
	ojciec_imie VARCHAR(40) NOT NULL, 
	narodowosc VARCHAR(40) NOT NULL, 
	obywatelstwo VARCHAR(40) NOT NULL, 
	urodzenie_miejsce VARCHAR(40) NOT NULL, 
	pesel VARCHAR(11) NOT NULL,
	dowod_osobisty_nr VARCHAR(10) not null,
	nip VARCHAR(20),
	telefon_nr VARCHAR(12) NOT NULL,
	mobile_nr VARCHAR(12),
	zameldowanie_ulica VARCHAR(45), 
	zameldowanie_dom_nr VARCHAR(6) NOT NULL, 
	zameldowanie_mieszkanie_nr VARCHAR(6), 
	zameldowanie_kod VARCHAR(6) NOT NULL, 
	zameldowanie_miasto VARCHAR(30) NOT NULL,
	zameldowanie_wojewodztwo VARCHAR(30) NOT NULL,
	korespondencja_ulica VARCHAR(45), 
	korespondencja_dom_nr VARCHAR(6), 
	korespondencja_mieszkanie_nr VARCHAR(6), 
	korespondencja_kod VARCHAR(6),
	korespondencja_miasto VARCHAR(30),
	korespondencja_wojewodztwo VARCHAR(30),
	kierunek VARCHAR(20) NOT NULL, 
	stacjonarne BOOLEAN DEFAULT true, 
	studia_typ VARCHAR(15) not null, 
	stosunek_do_sluzby_wojskowej VARCHAR(20) NOT NULL,
	wku_miasto VARCHAR(60),
	ksiazeczka_wojskowa_nr VARCHAR(20),
	niepelnosprawny BOOLEAN DEFAULT false, 
	login VARCHAR(20) NOT NULL, 
	haslo VARCHAR(32) NOT NULL, 
	specjalnosc VARCHAR(30), 
	jezyk VARCHAR(20), 
	jezyk2 VARCHAR(20), 
	szkola_srednia VARCHAR(255) not null,
	szkola_srednia_rok_ukonczenia VARCHAR(4), 
	inne_studia VARCHAR(255), 
	plywanie_grupa VARCHAR(20), 
	skad_wiem VARCHAR(40), 
	skonczone_studia VARCHAR(80), 
	skonczone_studia_rok_ukonczenia VARCHAR(4), 
	zdjecie VARCHAR(255),
	szkola_komentarz VARCHAR(255),
	przelew_zaksiegowany boolean default false,
	dokumenty_dotarly boolean default false,
	pytanie_haslo VARCHAR(80) not null default '',
	odpowiedz_haslo VARCHAR(25) not null default '',
	created_at TIMESTAMP, 
	updated_at TIMESTAMP, 
	PRIMARY KEY(id),
	UNIQUE(login)
) DEFAULT CHARSET=utf8;

CREATE TABLE admin (
	id SERIAL PRIMARY KEY,
	login VARCHAR(20) NOT NULL,
	haslo VARCHAR(32) NOT NULL,
	created_at TIMESTAMP, 
	updated_at TIMESTAMP, 
	UNIQUE(login)
) DEFAULT CHARSET=utf8;

insert into admin (login, haslo, created_at, updated_at) values ('rekrutacja', md5('zamek'), '2009-07-07 13:30', '2009-07-07 13:30');